config/routes.rb
Rails.application.routes.draw do
  resources :players, :tweets, :keywords
  root 'players#index'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	belongs_to :tweet
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :tweets
	belongs_to :position

end

app/models/position.rb
class Position < ActiveRecord::Base
	has_many :players
end

app/models/tweet.rb
require 'rubygems'
require 'twitter'

class Tweet < ActiveRecord::Base
	belongs_to :player
	belongs_to :keyword

	after_initialize(:init)

	def init
		@twitter = Twitter::REST::Client.new do |config|
		  	config.consumer_key = ENV["TWITTER_CONSUMER_KEY"]
		  	config.consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]
		  	config.access_token = ENV['TWITTER_ACCESS_TOKEN']
		  	config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
		end
	end

	def get_tweets(username)
		tweets = []
		bad_tweets = []
		good_label = ["family", "kids", "mom", "sponsor", "charity", "wife", "practice", "sleep", "weight room", "team", "fans", "girlfriend"]
		bad_label = ["beer", "hangover", "club", "party", "vegas", "drugs", "tired", "bieber", "shots", "injury", "bar", "arrest"]

		@twitter.search("@#{username} bieber OR tired OR club OR beer OR vegas", :result_type => "mixed").take(5).each do |tweet|
			# puts tweet.text
			# tweet_words = tweet.text.split(" ")
			# good = tweet_words.find {|word| good_label.include?(word)}
			# bad = tweet_words.find { |word| bad_label.include?(word)}
			# great_tweets << tweet.text if good
			# bad_tweets << tweet.text if bad
			tweets << tweet.text
		end
			tweets.join('<br><br>')
			# bad_tweets.join('<br><br>')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/players_controller.rb
require 'twitter'

class PlayersController < ApplicationController

	def index
		@players = Player.all

		# @list_of_tweets = Tweet.new.list_tweets(@player.twitter_username)
	end

	def show
		@player = Player.find(params[:id])

		@bad_tweets = Tweet.new.get_tweets(@player.twitter_username)


		# @good_tweets = Tweet.new.get_tweets(@player.twitter_username)

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<h2><%= link_to 'Fantasy Football Tracker', players_path %> </h2>
	<article><%= link_to 'Home', players_path %></article>
</header>

<%= yield %>

</body>
</html>

app/views/players/index.erb
<!-- Instructions -->
<div class="instruction">
	<p>Select a player to see how his off the field activity might impact your fantasy team on Sunday. </p>
</div>


<!-- List of Players -->
<div class="list-of-players">
<h3> Featured Players </h3>
<% @players.each do |player| %>
	<h4><%= link_to player.name, player_path(player.id) %></h4>
	<!-- link_to image_tag(t.photo_url), player_path(t.id) -->
<% end %>
</div>


<!-- Drop Down Menu -->
<div class="form">
	<p> Search by Position </p>
	<form action="/players/1" >                
	<select name="position_id">
		<option value=''>Quarterback</option>
		<% @players.where("position_id = 1").each do |player| %>
		  <option value="<%= player.position_id %>"><%= player.name %></option>
		<% end %>
	</select>
	<input type="submit" value="Submit">
	</form>

	<form action="/players/2" >
	<select name="position_id">
		<option value=''>Running Back</option>
		<% @players.where("position_id = 2").each do |player| %>
		  <option value="<%= player.position_id %>"><%= player.name %></option>
		<% end %>
	</select>
	<input type="submit" value="Submit">
	</form>

	<form action="/players/3" >
	<select name="position_id">
		<option value=''>Wide Receiver</option>
		<% @players.where("position_id = 3").each do |player| %>
		  <option value="<%= player.position_id %>"><%= player.name %></option>
		<% end %>
	</select>
	<input type="submit" value="Submit">
	</form>

	<form action="/players/4" >
	<select name="position_id">
		<option value=''>Tight End</option>
		<% @players.where("position_id = 4").each do |player| %>
		  <option value="<%= player.position_id %>"><%= player.name %></option>
		<% end %>
	</select>
	<input type="submit" value="Submit">
	</form>

	<form action="/players/5" >
	<select name="position_id">
		<option value=''>Cornerback</option>
		<% @players.where("position_id = 5").each do |player| %>
		  <option value="<%= player.position_id %>"><%= player.name %></option>
		<% end %>
	</select>
	<input type="submit" value="Submit">
	</form>
</div>

app/views/players/show.erb
<div class= "player-info">
	<h3><%= @player.name %></h3>
	Position: <%= @player.position.name %> <br>
	<%= @player.team %> <br>
	<%= image_tag(@player.photo_url)%>
</div>

<div class= "player-tweets">
	<p><strong>Reasons for Concern:</strong></p> <br>
	<p><%= @bad_tweets.html_safe %> </p>
	
</div>